[project]
name = "lambdalib"
version = "0.1.0"
description = "Lambdalib library of different core and toold for amaranth"
authors = [
    {name = "PO Vauboin", email = "po@lambdaconcept.com"},
    {name = "Pierre-Olivier Vauboin", email = "po@lambdaconcept.com"},
]
dependencies = [
    "setuptools>=69.0.2",
    "amaranth[builtin-yosys]~=0.4",
    "amaranth@git+https://github.com/amaranth-lang/amaranth-stdio",

]
requires-python = ">=3.10"
readme = "README.md"
license = {text = "MIT"}

[project.urls]
"Source Code" = "https://github.com/lambdaconcept/lambdalib"
"Bug Tracker" = "https://github.com/lambdaconcept/lambdalib/issues"


[build-system]
requires = ["wheel", "setuptools>=67.0", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
local_scheme = "node-and-timestamp"
